language: java

jdk:
  - openjdk17

# Need a full git clone in order to be able to tag the release
git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout $TRAVIS_BRANCH
  - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
  - gpg --fast-import .travis/gpg.asc

env:
  global:
    # Environment variables referenced in .travis/maven-settings.xml. To encrypt and escape values correctly, run the following
    # command and enter ENV_VAR=value when prompted:
    # read -r && travis encrypt "$(printf %q "$REPLY")"
    - secure: eW2WOP1JyPpxEVV9pdRysZ1MdwpwvaHiZHe0KyHrZaMu0d2+QIOInheGoZuWoEq72qXxQwXqPl9ayDQFeQyMXN9yNYXi+LFC/nhpePq3AZYW1Ca7aeVRSAtjRUhHCmQNP7b6jewL9l+T/uDJ1HKIBPQtPLhOxRijo8Qph/MpQMALwdhmyYlR9NuwxtiwlUJPFXIXsEB2kF2KVngqZ99GTVi/8yBNzVZSTcv6CVzBEzRa+SaJwsTmPBMP9aOUKmvENHq/35RR8DwiVgg8ytHTcferVcPIi/tlIZgQQGZ1uQyGG6ck4ccRnDq/DiohQtaX10yFmC1dvizsbyCpb77WkFGT+QZxMbeleCKGhONo2TY9w6CYJBgnKT963piTFQKGnoHYLqjoMzT+bCPNSU/Y27zNPDpJqB1sYojQf1BYvOcEp1d0QQgPw9PfQ5zLhjmz4lbaYacIseghXuLsrhiyKHETNlQaRyZOIHNwua+p0WhRYc9V9wnytvzuYP43Ys/2eOpBYgceydu8tNQ/40mT+7xWU66E5tCungR7j1IoMdFyUgO6dBZJHy2+RIE4My/a42Vpvu37HaxPK3fHihgI22I1+sHSlIJZrrV4rEsPNwg+8PgyZ1iOQTKaHO/UhoeJsf+hUZrrdjjxrpLsG/PdTYFzDrh/uuVvEbm5Yo0HQvQ=
    - secure: g30hZvC4IiQIqYvDoj3sQ5gbU6MYH6TE1X6OzSlxgtknTl/9uu8nJ7Qkc1XLgyKiV5p2iYZ+Jl1xP387lAdfYDZDlcUuNx+p04czE9siEAuRkIQgP5imk0E7rfMc75mu3lwh3haVq/ql/DrId2Tun+BNX+Q2atDdYTlHNYHyQK3TSCSLHo+G2FPLfd1vmBYRM/yGfC4iQD4ntR6w7Ztxt6/lneOFC249fk4EKaOD4IjwW8XG7XgSyBQijrj+Rpm/K1FySH5uXtNSubWua/ebyHlFeJcOgBz6swa7/p7E7hIKINZxibdhMxepviq9hf5lDJuPsXSu5XMbYLAF0obOYmnei65DgZMv/cXrzuzjFG4yn+GCmECMOQsaWsP/HeIa6zmR6vP5mltEqyiYLZPLTMn4beyasoZR7ltba+W+UhgoRLKT1/csHOHh8EQDni9EfDxl47kff8vm4xp35RwHbcBCzdpLSdEOIoeEkrqJmHOuAiy3mLK38GWpUlWY1EEOlHmOrTMfYn8snLerzXwk85t9Ri04TkgSv2tFnYdttLcPHiQK6lezNE61aIRDz2mQvUb5tJ5GYpZQtNnDIlBf3iwajc/9KAbr5oapIbdxd2emltFYD2TlbBM8o0cj1yCeANCaeG3vzGx6fVFaMfKzSmT40t/dWVDWXKN98KDEZMk=
    - secure: u/YA1g36nCGFR1Hp3H4NKS7/ZPv/HIoCO8WJSFsSOZNBCCTVe3PgsTXvCLYKV3Zjl1TTiQrF2b+1Pmfbpiay9x5R3MmUHM2DZ5zgbkGa5nqprdib79YcnQuMoZYdBdyMbmt5bqfcgcisD/ixg8O0dFvgHj2Cz/HtH7JIQ6TJ86szBdipO5yM7nSaTNjxWOSpvxb89Dp7nIYBPJGjBnc4uaWBUm31b/qG+1Dee4vU5zSCYLYrZ6gia8tN6ek4HGDjSTD7+aKWvyYTVi/BnFJDw/LhGUYczS4p1hKTeiC0KXPXoaRD6cyY1FCieJOe3ykPjGDdvWM+oFQkSFUlLNFIqTA1Au16hfoQFxqyAy/WzuB1x2QZfoms7JeNC4+VS7dIQG3W2Z2GIOPheRB5CbruEpm38rw/PYpVjaUYI6FZcI2CQWwCEZPg62l0BhNQduHmBCZmZnuUalJorCeUyO7bCzeQN4E86BINWHL48RbQmgmUg0LkXo4aQ5HeX/WALfS5tHV2ONLMwJSWdfq7djzpJqobCq6NbBCJiRDrAxlQuqkp3H0i0LOLIhJ0s7J6qQo4E41hqHhC0KH6g6MZymOsFoFhLw0IbjdCXlKdodRSbfuArTYYj0VyzREE53wzuHDxwzb9eBR/76zXBoYjr2+n9OwfeqRLZb5TDf52x88s7rU=
    - secure: UlXKnlJ8WcfH2yok9JD24lQ/4B5ZCqh0lmIPtM8iv6XNYFbBVINfeNdzkbamCW2qGzlMNQA/N8OFxcWu5mI3xu+2vddRSpIvg5zUS6lrVkWHMvxIE18orKO047jENjGv8aCbvI8xQIS6pAw41q50LyXTV2axOCCDEqndCIIAE3mXHmcQ2we0FUJINMSrKd6QpQaetuW0CEnfszs5n3KHX8PelzVwnhTvLU2Re4MQ3sFKqVfrtLtJjUXfxWT2ZDWQEdggHB6c98yz1B31rP4sL0r8jhtaan0UmMUmKI+cdl4PEGswVgyt7PpyHGRKsKLHqfCdvhF2v8kSMMZbr9adpEmWup5B47lVnvzkFaDLt4PcsxASkSxg/QDTeyrLoB7IwqBAm+/bOTO8KoTQPS0tSwQh8MWXCPqeuB+VSS3CA90kd4V5rC0iENOD4lNOpfB679SF1gJDS/uKm1LZAqpUoDs7fqo5q6PVTP0Asy/DiYUYmZiNtDNPg3SG8lU9+dxTbmFe1TkwQ2lfzOEZzjH4ixkz4REXQ8ZauvizayD9LnS01ThO/1rfySkqJJ3XYh1tY33HmHKgOj/UR6S0txB4PGHrhZ9To/UzT09gNgKft+PQd/Zj0llKUM25Xru9HxYIr6558Cp+GdkmkejrS60PrUAPvhVwy4sdO16C3dwh31Y=
    - secure: dWTRbr+O0mfkACogTnKvRKeY81QoMnA8NCKRDzrgP30QR3KJ/V/W81qEP19CyJAWwjRVYxL+mZizCI1sEY6baCM2SqVDAZjI0uvzeO2ve4d5Q9K1kcZa10bfE462IJbvCI2lgWhHZYmrbuTnJ4APcmGsjhO1iZzu//KzOaiWvQHyNsbBS5r9uD7zUKJI4c01pSzxi9g4+e6wZBravMRBlGpc9MW/w+vFEUkDnDris9RCsCDh3yAMhCbqH+2FZDRQg7xpjhayJgjAZvZ4B+fnHscaD0SCLXVAPfR8zaMMxPXZAyEXXlPbVOf+sVgOb68lS+cBFx7xHjAijCDbgoqynTFlwfKOZU6ieT12AJLXtYvCzxEdIRNN5s4RbU7NWCXQLNi+F3erkkFIyQ2Luecj0B7w/qdHCYrXMrA2JrHle+ZpzaM3+Yyh1V6sMTJsIG2FvmIwxvoHzUbV5o9Mgmqo+ziv/Pr+5iKFywd5RuzY4et2YP74szHgdbZ54QmvUwVQqpCY8yyC5b1W/pPvrhTke2BBQi3/exmvsXA/LTka4gn3f0il9giiSZzT7Wuu49gBa2Rv/HetjOhJQdjUzsXFN8HW+fXEBo8wveebc4XbUo94f8sIc9n2YM3tcjw1AXJ/NBiYPYdM+gugd+RCJ+dKABEklW14mTM8FN22/yoCifo=

script:
  - mvn clean install -B
  - mvn org.pitest:pitest-maven:mutationCoverage -B

before_deploy:
  # Set tag to be used by releases provider
  - export TRAVIS_TAG=$POM_VERSION

deploy:
  # For any checkin to main branch, create a final version, tag it and push the artifacts to Sonatype
  - provider: script
    skip_cleanup: true
    script:
      mvn --settings .travis/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
    on:
      branch: main

  # Releases config copied from https://docs.travis-ci.com/user/deployment/releases/ and secure key generated by following
  # https://stackoverflow.com/questions/25302518/travis-ci-setup-releases-with-github-token#answer-57032190
  - provider: releases
    api_key:
      secure: XxzUQdpni9P5kPGKPqmFQhlDL9+hz3QRyhDMZz1sdaITSMte3LMo88PR6nSkgqzmfDmjIzQluysEivmwujQeiFWLYWD06TvDseLleTxqWw6+z8dGmvDjhfnwQPEMxegDOFMPzTFnzfIlR9/ux4i3fcxtcx6LJCc5JZ2iL960Dnts6RT/13W9A0OV3YkmaERwcl9xQKbQniB+WKnmbbX/Sv1SBh6lRxoeP1zFuTJ3p8Qq1BO6RCFJUgWtvYQ0D10jACeWCVmbKAaAP1waXjOjjKqulKHEDoArQNMLMNvt7xSsE+m6n8UCxE3PEjfHP6jt9z4CAv63mkMN+a3Qt6Vkz3OIjEXiDLWl4+hhKshEmdImB3GFaGgTRMJSaNvVh1akQdO8c9rVth5rRkRfpp4Fs/QAqQZzIMK5wRDuFHUAFft+anV/JfNCqN+GrC6vckoYyL3gJzHFOqg65VhUAuZgHH2P7Cv5pOc7qSacmlmwZ1H1JPNL/Yn6mR52rkqdLvpKHz7+nU34eYVQv2lI2HVPsGmf9dyW/uOvtCiPuje4+XZhb8PdczV3wMhQarfV07HYUXS4CwjVPNCFZdOvXohndxhOo7+vIEARqKWgFfLxYdmqqmdpvxdOQh+XJTZIXAj7Pdb1nfBBjjuB0EY3fU9zZC41vFy8KUg6yZHEqDV0KBA=
    file: "target/spt-development-cid-web-${POM_VERSION}.jar"
    skip_cleanup: true
    on:
      branch: main